app/models.py
from . import db
from flask_login import UserMixin
from . import login_manager





class Users(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String)
    password = db.Column(db.String) 
    #Relationship
    pitches = db.relationship('Pitch', backref='owner')
    comments = db.relationship('Comment', backref='owner')

    def __repr__(self):
        return f"Users('{self.username}')"

    @login_manager.user_loader
    def load_user(user_id):
        return Users.query.get(int(user_id))

class Pitch(db.Model):
    '''
    '''
    __tablename__ = 'pitches'
#one to many classes relationship
    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    description = db.Column(db.String(), index=True)
    title = db.Column(db.String())
    category = db.Column(db.String(255), nullable=False)  
    def __repr__(self):
            return f'Pitch {self.description}' 

class Comment(db.Model):
    '''
    '''
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    content = db.Column(db.String(255), index=True)
   
 
    def __repr__(self):
            return f'Comment {self.content}'   

app/main/forms.py
from wtforms import StringField, PasswordField, BooleanField
from flask_wtf import FlaskForm, form
from wtforms.validators import InputRequired, Email
from wtforms.widgets import TextArea

class LoginForm(FlaskForm):
    username = StringField('Username',validators=[InputRequired()])
    password = PasswordField('Password',validators=[InputRequired()])
    remember = BooleanField('Remember')
    
class RegisterForm(FlaskForm):
    
    email = StringField('Email', validators=[InputRequired(), Email()])
    username = StringField('username',validators=[InputRequired()])   
    password = PasswordField('Password',validators=[InputRequired()])
    
    
class PitchForm(FlaskForm):
    
    title = StringField('Title of pitch',validators=[InputRequired()])
    category = StringField('Category: Innovation, Business or Pickup Line',validators=[InputRequired()])
    description = StringField('Pitch',validators=[InputRequired()], widget=TextArea())
    
class CommentForm(FlaskForm):
    content = StringField('Comment')   

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager



login_manager = LoginManager()
login_manager.login_view = 'login'
bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
 # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for
from flask_wtf import FlaskForm
from .forms import LoginForm, RegisterForm, PitchForm, CommentForm
from ..models import Users, Pitch, Comment
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import LoginManager, UserMixin, login_required, login_user, logout_user, current_user
from . import main
from .. import db

# Views
@main.route('/')
def index():
    title = "Home page"
    return render_template('index.html', title = title)

@main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
       
        new_user = Users(username=form.username.data, email=form.email.data, password=hashed_password)
    
        db.session.add(new_user)
        db.session.commit()
        return redirect('/success')
    return render_template('signup.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('main.dashboard'))
         
        return redirect('failure')
    
  
    return render_template('login.html', form=form )

@main.route('/success')
def success():
    
    return render_template('success.html')

@main.route('/success')
def failure():
    
    return render_template('failure.html')

@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    pitch = Pitch.query.all()
    
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(owner_id=current_user.id, content=form.content.data)
        form.content.data = ''
       
        
        db.session.add(comment)
        db.session.commit()
    return render_template('dashboard.html', name=current_user.username, pitch=pitch, form=form, content=form.content.data)

@main.route('/pitch', methods=['GET', 'POST'])
@login_required
def pitch():
    form = PitchForm()
    
    if form.validate_on_submit():
        pitch = Pitch(owner_id=current_user.id, title=form.title.data, category=form.category.data, description=form.description.data)
        form.title.data = ''
        form.category.data = ''
        form.description.data = ''
        
        db.session.add(pitch)
        db.session.commit()
    return render_template('pitch.html', form=form)

@main.route('/profile')
@login_required
def profile():
    
    pitch = Pitch.query.filter_by(id=current_user.id).all()
    
    return render_template('profile.html', name=current_user.username, email=current_user.email, password=current_user.password, pitch=pitch)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/views.py
from flask import render_template
from app import app

# Views
@app.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title = "Home page"
    return render_template('index.html', title = title)

@app.route('/signup/<signup_id>')
def signup():
    """
    View sign up page
    """
    return render_template('signup.html')

app/templates/dashboard.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container-fluid nav text-center">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <h3>PITCHY2.0</h3>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{ url_for('main.profile')}}">
                <h3>PROFILE</h3>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{url_for('main.logout')}}">
                <h3>LOGOUT</h3>
            </a>
        </div>
    </div>

</div>

<div class="container text-center">
    <h1 class="welcome">Welcome, {{ name | capitalize }}</h1>
    <p>Pitchy allows you to put forth pitches in various categories. <br> 
        Pitchy also allows you to interact with various People and view their Pitches 🍑.<br>
    Knowledge is power and Pitchy is here to share the experience with you</p>
</div>

<div class="container-fluid categories">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body text-center">
                    <h4 class="card-title">BUSINESS PITCH <br>💸</h4>
                    <p class="card-text">A promising business idea that will be guaranteed to take off.</p>
                    <a href="{{ url_for('main.pitch') }}" class="btn btn-primary">Submit Your Pitch</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body text-center">
                    <h4 class="card-title">INNOVATION PITCH <br>💡</h4>
                    <p class="card-text">A new and exciting idea, relevant for the present times.</p>
                    <a href="{{ url_for('main.pitch') }}" class="btn btn-primary">Submit Your Pitch</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body text-center">
                    <h4 class="card-title">PICKUP LINE <br>🥰😂</h4>
                    <p class="card-text">Creative pick-up lines that will make you unforgettable!</p>
                    <a href="{{ url_for('main.pitch') }}" class="btn btn-primary">Submit Your Pitch</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <h3>BELOW ARE VARIOUS SUBMITTED PITCHES</h3>
    <h5>Explore more:</h5>

</div>
<div class="container pitches-section">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">

            {% for p in pitch %}
            <p>TITLE: {{p.title}} </p>
            <p>CATEGORY: {{p.category}}</p>
            <p>PITCH: {{p.description}}</p>
            <p>Submitted by: {{p.owner.username}}</p>


            <form class="form-signin" method="POST" action="/dashboard">
                {{ form.hidden_tag() }}
                {{ wtf.form_field(form.content) }}
                <button class="btn btn-lg btn-primary btn-block comment-btn" type="submit">Comment</button>
            </form>
            <hr>
            {% endfor %}
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            {% for comment in comments %}
            <p> {{comment.content}}</p>

            {% endfor %}
        </div>


    </div>

</div>
{% endblock %}

app/templates/failure.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}


{% block content %}

<div class="jumbotron failure jumbotron-fluid text-center">
    <div class="container">
      <h2 class="display-4">SORRY</h2> 
      <p class="lead">Invalid password or username.</p>
      <a href="{{ url_for('main.login') }}"><button class="btn again btn-primary">Try Again</button></a>
    </div>
  </div>
{% endblock %}

app/templates/index.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}
{% block content%}

<div class="container-fluid">
    <div class="jumbotron text-center">
        <p class='wrd'>Welcome to</p>
        <h1 class="display-4 intro">PITCHY</h1>
        <p class='wrd'>Gone in Sixty Seconds</p>

        <a href="{{ url_for('main.signup') }}"><button class="btn btn-light">Sign-up</button></a>
        <a href="{{ url_for('main.login') }}"><button type="button" class="btn btn-dark">Login</button></a>
    </div>
</div>


{% endblock %}

app/templates/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Login
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block content %}
<a href="{{ url_for('main.index') }}"><button class="btn back btn-primary">Back</button></a>
<div class="container signup text-center">

  <form class="form-signin" method="POST" action="/login">
    <h4 class="form-signin-heading">Please Login to Continue</h4>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.password) }}


    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  </form>

</div>

{% endblock%}

app/templates/pitch.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}


{% block content %}
<a href="{{url_for('main.dashboard')}}"><button class="btn btn-primary home">Home</button></a>
<div class="container signup text-center">

    <form class="form-signin" method="POST" action="/pitch">
      <h4 class="form-signin-heading">Add Your Pitch Here</h4>
      {{ form.hidden_tag() }}
      {{ wtf.form_field(form.title) }}
      {{ wtf.form_field(form.category) }}
      {{ wtf.form_field(form.description) }}
  
      <button class="btn btn-lg btn-primary btn-block" type="submit">Submit Pitch</button>
    </form>

{% endblock %}

app/templates/profile.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container-fluid nav text-center">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{url_for('main.dashboard')}}">
                <h3>DASHBOARD</h3>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{ url_for('main.profile')}}">
                <h3>PROFILE</h3>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <a class="nav-link" href="{{url_for('main.logout')}}">
                <h3>LOGOUT</h3>
            </a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6">
            <h3>USER INFORMATION</h3>
            <p>USERNAME: {{ name }}</p>
            <p>USER EMAIL ADDRESS: {{ email }}</p>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-6">
            <h3>PITCHES SUBMITTED</h3>
            <div>
                {% for p in pitch %}
                <p>Title: {{p.title}} </p>
                <p>Category: {{p.category}}</p>
                <p>Content of the pitch: {{p.description}}</p>
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Sign Up
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block content %}
<a href="{{ url_for('main.index') }}"><button class="btn back btn-primary">Back</button></a>
<div class="container signup text-center">
  <form class="form-signin" method="POST" action="/signup">
    <h2 class="form-signin-heading">Sign Up</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.password) }}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
  </form>
</div> 
{% endblock %}

app/templates/success.html
{% extends "bootstrap/base.html" %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link
    href="https://fonts.googleapis.com/css2?family=Lora&family=Nunito:wght@200&family=Quicksand&family=Roboto&family=Roboto+Slab:wght@300;400&family=Zen+Antique&display=swap"
    rel="stylesheet">
{% endblock %}


{% block content %}

<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
      <h2 class="display-4">CONGRATULATIONS!</h2> 
      <p class="lead">You have successfully created a Pitchy account</p>
      <a href="{{ url_for('main.login') }}"><button class="btn btn-primary">Proceed to Login</button></a>
    </div>
  </div>
{% endblock %}